# Prettier configuration for Markdown formatting
# See: https://prettier.io/docs/en/options.html

# Only format markdown files
overrides:
  - files: "*.md"
    options:
      proseWrap: preserve
      printWidth: 120
      tabWidth: 2
      useTabs: false
